[versions]
mod-version = "0.9.3"

# Fabric (https://fabricmc.net/develop)
jdk = "25"
minecraft = "26.2"
fabric-loader = "0.19.3"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.17-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "26.2-SNAPSHOT"

# Test
junit = "5.11.3"

# Mods
[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

# Test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

# Mods

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
